# Generated by Django 3.0.2 on 2020-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TryOn', '0005_auto_20200218_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.BigIntegerField()),
                ('category', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('imgeurl', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
