# Generated by Django 3.0.2 on 2020-02-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TryOn', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
