# Generated by Django 3.0.2 on 2020-02-23 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TryOn', '0007_auto_20200222_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TryOn.Product'),
        ),
    ]
