# Generated by Django 3.0.3 on 2020-03-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TryOn', '0008_auto_20200224_0041'),
        ('TryOn', '0008_auto_20200225_2026'),
    ]

    operations = [
    ]
