# Generated by Django 3.0.3 on 2020-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TryOnVendor', '0002_auto_20200226_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.FileField(max_length=300, upload_to=''),
        ),
    ]
