# Generated by Django 3.0.3 on 2020-02-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TryOnVendor', '0003_auto_20200227_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address_proof',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='permit_document',
            field=models.ImageField(upload_to='img'),
        ),
    ]
