# Generated by Django 3.0.3 on 2020-02-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TryOnVendor', '0005_auto_20200228_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_id',
            field=models.IntegerField(),
        ),
    ]
