# Generated by Django 3.0.3 on 2020-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TryOnVendor', '0006_auto_20200228_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(max_length=300, upload_to=''),
        ),
    ]
